export const FETCH_INVENTORY_REQUEST = 'FETCH_INVENTORY_REQUEST';
export const FETCH_INVENTORY_SUCCESS = 'FETCH_INVENTORY_SUCCESS';
export const FETCH_INVENTORY_FAILURE = 'FETCH_INVENTORY_FAILURE';

export const ADD_INVENTORY_ITEM_REQUEST = 'ADD_INVENTORY_ITEM_REQUEST';
export const ADD_INVENTORY_ITEM_SUCCESS = 'ADD_INVENTORY_ITEM_SUCCESS';
export const ADD_INVENTORY_ITEM_FAILURE = 'ADD_INVENTORY_ITEM_FAILURE';

export const TRANSFER_INVENTORY_REQUEST = 'TRANSFER_INVENTORY_REQUEST';
export const TRANSFER_INVENTORY_SUCCESS = 'TRANSFER_INVENTORY_SUCCESS';
export const TRANSFER_INVENTORY_FAILURE = 'TRANSFER_INVENTORY_FAILURE';

export const UPDATE_INVENTORY_REQUEST = 'UPDATE_INVENTORY_REQUEST';
export const UPDATE_INVENTORY_SUCCESS = 'UPDATE_INVENTORY_SUCCESS';
export const UPDATE_INVENTORY_FAILURE = 'UPDATE_INVENTORY_FAILURE';

export const RESTOCK_INVENTORY_REQUEST = 'RESTOCK_INVENTORY_REQUEST';
export const RESTOCK_INVENTORY_SUCCESS = 'RESTOCK_INVENTORY_SUCCESS';
export const RESTOCK_INVENTORY_FAILURE = 'RESTOCK_INVENTORY_FAILURE';
